version: "3"

services:
  client:
    image: nginx
    container_name: nginx-web
    ports:
      - 80:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./site.conf:/etc/nginx/conf.d/site.conf
